### ISSUE TITLE
Add documentation to explain how to pass command line options

### ISSUE THREAD

**Issue by polentino** [gradle/playframework#121]
The [User Manual](https://gradle.github.io/playframework/) doesn't have any paragraph explaining how to add arbitrary command line options to the `runPlay` gradle task; the closest I got, googling around, is
```
tasks.withType(PlayRun) {
    forkOptions.jvmArgs = [....]
}
```
Problem is,  `PlayRun` task is marked as deprecated.. So what is the idiomatic way to do it?

**Comment by big-guy** [comment]
`PlayRun` is marked deprecated in the bundled Gradle Play plugin.  There's an equivalent task in the external play plugin (this repository) that's not deprecated.  It's also called `PlayRun` because it started out as a copy of the original task.

I think what you're trying it about right.  We could probably make it easier by hiding the `ForkOptions` behind explicit task properties instead of exposing it.  That's just how the old task was implemented.

**Comment by polentino** [comment]
that is odd: I'm using plugin version `0.9` with gradle `5.6`, and IntelliJ does mark the task as deprecated: if I navigate into its source, it is indeed annotated as follows
```
@Incubating
@Deprecated
public class PlayRun extends ConventionTask {
    private static final Logger LOGGER = LoggerFactory.getLogger(PlayRun.class);

    private int httpPort;
```
however, the sourcecode in here doesn't have these annotations (https://github.com/gradle/playframework/blob/v0.9/src/main/java/org/gradle/playframework/tasks/PlayRun.java)... clearly a problem on my side which I need to figure out, thx for the explanation :)

**Comment by big-guy** [comment]
Yep, that's the built-in PlayRun (which gets imported automatically) and not this plugin's version.
