### ISSUE TITLE
Plugin DSL should provide the ability to define a target Play platform of compatible Scala and Java versions

### ISSUE THREAD

**Issue by bmuschko** [gradle/playframework#69]
The old plugin allows users to provide a target Play platform. A target Play platform automatically determines compatible Scala and Java versions and uses them for the project.

```
model {
    components {
        play {
            targetPlatform 'play-2.4.0'
        }
    }
}
```

The logic that determines the compatible Scala and Java versions is available in [`PlayPlatformResolver`](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/internal/PlayPlatformResolver.java) and [`PlayMajorVersion`](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/internal/platform/PlayMajorVersion.java). The [Gradle user guide for the Play plugin](https://docs.gradle.org/current/userguide/play_plugin.html) doesn't document the feature so I am not sure if it was intended for end users.

Should the new plugin provide similar functionality or do we want users to explicitly provide the Play, Scala and Java version through the DSL without trying to be too smart? At the moment the new plugin only uses the default Scala and Java versions independent of the assigned Play version.

**Comment by big-guy** [comment]
For the specific `targetPlatform 'play-2.4.0'` sort of syntax, I think, no, we don't need to support that.

I would suggest moving
https://github.com/gradle/play/blob/c1bfd9546bda50cec4ac8829691cd1016e281db4/src/main/java/com/playframework/gradle/plugins/PlayApplicationPlugin.java#L81-L88
into the extension's constructor. It's possible (but unlikely) that someone can set the default value of the property before that particular bit of code runs.

I believe the old plugin always used the current JVM as the version of Java, regardless of the version of Play, unless explicitly selected.  The new plugin doesn't need to do any better than that.

I've gone back and forth on it.  Since we need it for testing anyways, I think we should keep a short mapping of major playVersion -> specific scalaVersion and change the initial value of scalaVersion to:

`scalaVersion.set(playVersion.map(play -> lookupVersionOfScalaFor(play))`

Where `lookupVersionOfScalaFor` looks at the mapping and picks the best choice.  When we don't know which version to use with Play, we should pick some default value.

This means for users they would do:
```
play {
   platform.playVersion = "2.6.2"
}
```

And scalaVersion would automagically be selected.

How does that sound?

**Comment by bmuschko** [comment]
> I've gone back and forth on it. Since we need it for testing anyways...

I implemented a [simple solution](https://github.com/gradle/play/blob/master/src/integTestFixtures/groovy/org/gradle/playframework/fixtures/multiversion/TargetPlatform.groovy#L30-L40) for testing purposes but let me look into your comments here.

**Comment by bmuschko** [comment]
Implementation: https://github.com/gradle/play/commit/9e918652c32afb0d061b950ed708d64bdd36b012, https://github.com/gradle/play/commit/8bc6c327c93695683201b70f1e5d0332978df2d9
